//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bromo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BromoAirlinesEntities1 : DbContext
    {
        public BromoAirlinesEntities1()
            : base("name=BromoAirlinesEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Akun> Akun { get; set; }
        public virtual DbSet<Bandara> Bandara { get; set; }
        public virtual DbSet<JadwalPenerbangan> JadwalPenerbangan { get; set; }
        public virtual DbSet<KodePromo> KodePromo { get; set; }
        public virtual DbSet<Maskapai> Maskapai { get; set; }
        public virtual DbSet<Negara> Negara { get; set; }
        public virtual DbSet<PerubahanStatusJadwalPenerbangan> PerubahanStatusJadwalPenerbangan { get; set; }
        public virtual DbSet<StatusPenerbangan> StatusPenerbangan { get; set; }
        public virtual DbSet<TransaksiDetail> TransaksiDetail { get; set; }
        public virtual DbSet<TransaksiHeader> TransaksiHeader { get; set; }
    }
}
